name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set based on branch
        run: |
          echo "IMAGE_TAG=$(if [ ${{ github.ref }} == 'refs/heads/main' ]; then echo latest; else echo latest-dev; fi)" >> $GITHUB_ENV
          echo "RUN_SERVICE=$(if [ ${{ github.ref }} == 'refs/heads/main' ]; then echo waterwise; else echo waterwise-dev; fi)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: c241-ps478

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }}

      - name: Push to Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker push asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }}

      - name: Deploy to Google Run
        run: |
          gcloud run deploy ${{ env.RUN_SERVICE }} \
            --image asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }} \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --port 5000 \
            --v