name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
      - prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Set variables based on branch
        run: |
          echo "IMAGE_TAG=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo latest; else echo latest-dev; fi)" >> $GITHUB_ENV
          echo "RUN_SERVICE=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo waterwise; else echo waterwise-dev; fi)" >> $GITHUB_ENV
          echo "NODE_ENV=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo production; else echo development; fi)" >> $GITHUB_ENV
          echo "DATABASE_URL=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo ${{ secrets.DATABASE_URL }}; else echo ${{ secrets.DATABASE_URL_DEV }}; fi)" >> $GITHUB_ENV
          echo "GCS_BUCKET=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo ${{ secrets.GCS_BUCKET }}; else echo ${{ secrets.GCS_BUCKET_DEV }}; fi)" >> $GITHUB_ENV
          echo "SECRET_KEY=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo ${{ secrets.SECRET_KEY }}; else echo ${{ secrets.SECRET_KEY_DEV }}; fi)" >> $GITHUB_ENV
          echo "GEOCODING_API_KEY=$(if [ ${{ github.ref }} == 'refs/heads/prod' ]; then echo ${{ secrets.GEOCODING_API_KEY }}; else echo ${{ secrets.GEOCODING_API_KEY_DEV }}; fi)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Migrate database
        run: npm run migrate deploy

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: c241-ps478

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }}

      - name: Push to Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker push asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.RUN_SERVICE }} \
            --image asia-east1-docker.pkg.dev/c241-ps478/waterwise/main-backend:${{ env.IMAGE_TAG }} \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --port 3000 \
            --max-instances 3 \
            --set-env-vars "NODE_ENV=production" \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --set-env-vars "ML_API_URL=${{ secrets.ML_API_URL }}" \
            --set-env-vars "GCS_BUCKET=${{ env.GCS_BUCKET }}" \
            --set-env-vars "SECRET_KEY=${{ env.SECRET_KEY }}" \
            --set-env-vars "GEOCODING_API_KEY=${{ secrets.GEOCODING_API_KEY }}" \